// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/messenger-apigateway/internal/app/adapter/auth"
	"github.com/TemaKut/messenger-apigateway/internal/app/config"
	"github.com/TemaKut/messenger-apigateway/internal/app/handler/websocket"
	"github.com/TemaKut/messenger-apigateway/internal/service/delegate"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return App{}, nil, err
	}
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return App{}, nil, err
	}
	userAPIClient, cleanup, err := ProvideUserApiGrpcClient(configConfig, logger)
	if err != nil {
		return App{}, nil, err
	}
	adapter := auth.NewAdapter(userAPIClient)
	service := delegatesvc.NewService(adapter)
	handler := websocket.NewHandler(service, logger)
	httpServerProvider, err := ProvideHttpServerProvider(configConfig, handler)
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	httpProvider := ProvideHttpProvider(httpServerProvider)
	app, cleanup2 := ProvideApp(logger, httpProvider)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
