// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/messenger-apigateway/internal/app/config"
	"github.com/TemaKut/messenger-apigateway/internal/app/handler/websocket"
	"github.com/TemaKut/messenger-apigateway/internal/app/handler/websocket/controllers"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	configConfig := config.NewConfig()
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return App{}, nil, err
	}
	userRegisterControllerImpl := controllers.NewUserRegisterControllerImpl()
	controller := controllers.NewController(userRegisterControllerImpl)
	handler := websocket.NewHandler(controller, logger)
	httpServerProvider, err := ProvideHttpServerProvider(configConfig, handler)
	if err != nil {
		return App{}, nil, err
	}
	httpProvider := ProvideHttpProvider(httpServerProvider)
	app, cleanup := ProvideApp(logger, httpProvider)
	return app, func() {
		cleanup()
	}, nil
}
