// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	logger, err := ProvideLogger()
	if err != nil {
		return App{}, nil, err
	}
	app, cleanup := ProvideApp(logger)
	return app, func() {
		cleanup()
	}, nil
}
